name: Update README with Latest Photo and Blog Posts

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install feedparser

      - name: Run update script
        run: |
          echo "Running Python update script..."
          python update_readme.py
          echo "Script completed."

      - name: Check git status
        run: |
          echo "::group::Git Status"
          git status
          echo "::endgroup::"

          echo "::group::Git Diff"
          git diff
          echo "::endgroup::"

          echo "::group::Git Diff (cached)"
          git diff --cached
          echo "::endgroup::"

      - name: Commit and push if changes
        run: |
          set -x
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md

          if git diff --cached --quiet; then
            echo "✅ No changes to commit."
          else
            echo "🔁 Committing and pushing changes..."
            git commit -m "Update README with latest photo and blog posts"
            git push
          fi
